### ISSUE TITLE
No support for v2 registry API endpoint

### ISSUE THREAD

**Issue by twaugh** [yodle/docker-registry-client#2]
The v2 API (https://docs.docker.com/registry/spec/api/) is not supported.

I'm looking for a Python client for the Docker v2 registry, and this seems like the best fit. The only part missing is v2 support. :-)

Would you consider accepting this if I started work on it?

**Comment by munk** [comment]
I absolutely would!

**Comment by Seb-Solon** [comment]
I guess this can be closed

**Comment by twaugh** [comment]
I guess so. There's probably more support to add but the majority of the read-only parts are there.
