### ISSUE TITLE
QUESTION: Can this be used to clone a private docker registry?

### ISSUE THREAD

**Issue by frakman1** [yodle/docker-registry-client#58]
I have a private docker registry using the docker contrainer `registry registry:2`. Let's call it `myregistry1`
I want to create a second identical registry, `myregistry2` but without disturbing the original running one. So no shutting down, cloning drive etc.

I can create a new, empty `myregistry2` on a second machine using the same docker container method `registry registry:2`

Is there a script I can run that uses the REST API or ssh to copy all the docker images and associated metadata from `myregistry1` to `myregistry2` over the network?

I was thinking of using this library or something similar to loop over all the images of `myregistry1` and push them to `myregistry2` but don't know how.

**Comment by djmattyg007** [comment]
I think the easiest way to do this is with a tool named `skopeo`. For each repository you should run something like this:

```
skopeo sync --all --src docker --dest docker registry1.com/${REPO} registry2.com
```

**Comment by frakman1** [comment]
Thank you for the suggestion. I think I looked into skopeo once.

For anyone else looking at this issue, I was able to get this to work using this project with the help of the developer:
https://github.com/regclient/regclient

See this issue for details:
https://github.com/regclient/regclient/issues/64
